'use client';

import { useState, type FormEvent, type ReactNode } from 'react';
import { createAddon, createCategory, createOption, createProduct, loadAdminMenu, updateAddon, updateAvailability, updateCategory, updateOption, updateProduct } from '@/app/admin/cardapio/actions';
import type { AdminMenuAddon, AdminMenuCategory, AdminMenuData, AdminMenuOption, AdminMenuProduct, AdminMenuResult, MenuMutationResult } from '@/lib/admin-menu-types';
import { Badge, Button, Card, Money } from '@/components/ui';

type Modal = { kind: 'category'; value?: AdminMenuCategory } | { kind: 'product'; value?: AdminMenuProduct } | { kind: 'extras'; value: AdminMenuProduct };
const str = (form: FormData, key: string) => String(form.get(key) ?? '');
const num = (form: FormData, key: string) => Number(form.get(key));
const checked = (form: FormData, key: string) => form.get(key) === 'on';

export function MenuAdmin({ initial }: { initial: AdminMenuResult }) {
  const [data, setData] = useState<AdminMenuData | null>(initial.data ?? null);
  const [error, setError] = useState(initial.error ?? null);
  const [notice, setNotice] = useState('');
  const [saving, setSaving] = useState(false);
  const [modal, setModal] = useState<Modal | null>(null);

  async function refresh() {
    const result = await loadAdminMenu();
    if (result.data) { setData(result.data); setError(null); }
    else setError(result.error);
  }
  async function mutate(operation: Promise<MenuMutationResult>, close = false) {
    if (saving) return;
    setSaving(true); setError(null); setNotice('');
    try {
      const result = await operation;
      if (result.data) { setNotice(result.data.message); await refresh(); if (close) setModal(null); }
      else { setError(result.error); if (result.conflict) await refresh(); }
    } catch { setError('A conexão foi interrompida. Atualize os dados e tente novamente.'); }
    finally { setSaving(false); }
  }
  if (!data) return <Card><p role="alert" className="text-red-700">{error ?? 'Cardápio indisponível.'}</p><Button onClick={() => void refresh()} className="mt-3">Tentar novamente</Button></Card>;
  const categoryName = new Map(data.categories.map(category => [category.id, category.name]));
  return <>
    <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-black">Cardápio</h1><p className="mt-1 text-stone-600">Produtos e disponibilidade de {data.date.split('-').reverse().join('/')}.</p></div><div className="flex gap-2"><Button onClick={() => setModal({ kind: 'category' })}>+ Categoria</Button><Button onClick={() => setModal({ kind: 'product' })}>+ Criar produto</Button></div></div>
    {error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <p role="status" className="mt-3 text-sm text-green-700">{saving ? 'Salvando...' : notice}</p>
    <Card className="mt-5"><div className="flex items-center justify-between"><h2 className="font-black">Categorias</h2><button onClick={() => void refresh()} disabled={saving} className="text-sm font-semibold text-brand-700">Atualizar</button></div><div className="mt-3 flex flex-wrap gap-2">{data.categories.map(category => <button key={category.id} onClick={() => setModal({ kind: 'category', value: category })} className="rounded-xl border bg-white px-3 py-2 text-sm"><b>{category.name}</b> · ordem {category.sort_order} · {category.active ? 'ativa' : 'inativa'}</button>)}{data.categories.length === 0 && <p className="text-sm text-stone-500">Nenhuma categoria cadastrada.</p>}</div></Card>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><h2 className="font-black">Produtos cadastrados</h2><div className="mt-4 space-y-3">{data.products.map(product => <div className="rounded-xl border p-3" key={product.id}><div className="flex justify-between gap-3"><div><b>{product.image_url || '🍽️'} {product.name}</b><p className="text-sm text-stone-500"><Money value={product.price_cents / 100}/> · {categoryName.get(product.category_id) ?? 'Sem categoria'} · ordem {product.sort_order}</p></div><Badge tone={product.active ? 'green' : 'stone'}>{product.active ? 'Ativo' : 'Inativo'}</Badge></div><div className="mt-3 flex flex-wrap gap-2 text-xs"><button onClick={() => setModal({ kind: 'product', value: product })} className="rounded-lg bg-stone-100 px-2 py-1">Editar</button><button onClick={() => setModal({ kind: 'extras', value: product })} className="rounded-lg bg-stone-100 px-2 py-1">Opções e adicionais ({product.addons.length})</button></div></div>)}{data.products.length === 0 && <p className="text-sm text-stone-500">Nenhum produto cadastrado.</p>}</div></Card>
      <Card><h2 className="font-black">Cardápio disponível hoje</h2><p className="mt-1 text-sm text-stone-500">Disponibilidade da data comercial de São Paulo.</p><div className="mt-4 space-y-3">{data.products.map(product => { const daily = product.availability; return <div key={product.id} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><span><b>{product.name}</b><br/><small>{!daily?.available_today ? 'Fora do cardápio' : daily.sold_out ? 'Esgotado' : 'Disponível'} · ordem {daily?.sort_order ?? product.sort_order}</small></span><Badge tone={!daily?.available_today ? 'stone' : daily.sold_out ? 'red' : 'green'}>{!daily?.available_today ? 'Indisponível' : daily.sold_out ? 'Esgotado' : 'Disponível'}</Badge></div><div className="mt-3 flex flex-wrap gap-2 text-xs"><button disabled={saving} onClick={() => void mutate(updateAvailability({ productId: product.id, availableToday: true, soldOut: false, sortOrder: daily?.sort_order ?? product.sort_order, updatedAt: daily?.updated_at ?? null }))} className="rounded-lg bg-green-50 px-2 py-1 text-green-800">Disponibilizar</button><button disabled={saving} onClick={() => void mutate(updateAvailability({ productId: product.id, availableToday: true, soldOut: true, sortOrder: daily?.sort_order ?? product.sort_order, updatedAt: daily?.updated_at ?? null }))} className="rounded-lg bg-red-50 px-2 py-1 text-red-700">Esgotado</button><button disabled={saving} onClick={() => void mutate(updateAvailability({ productId: product.id, availableToday: false, soldOut: false, sortOrder: daily?.sort_order ?? product.sort_order, updatedAt: daily?.updated_at ?? null }))} className="rounded-lg bg-stone-100 px-2 py-1">Retirar de hoje</button></div></div>; })}</div></Card>
    </div>
    {modal?.kind === 'category' && <CategoryModal value={modal.value} saving={saving} close={() => setModal(null)} submit={(form, value) => void mutate(value ? updateCategory({ id: value.id, name: str(form,'name'), sortOrder: num(form,'sortOrder'), active: checked(form,'active'), updatedAt: value.updated_at }) : createCategory({ name: str(form,'name'), sortOrder: num(form,'sortOrder') }), true)} />}
    {modal?.kind === 'product' && <ProductModal value={modal.value} categories={data.categories} saving={saving} close={() => setModal(null)} submit={(form, value) => { const input = { categoryId: str(form,'categoryId'), name: str(form,'name'), description: str(form,'description'), price: str(form,'price'), imageUrl: str(form,'imageUrl'), sortOrder: num(form,'sortOrder'), active: checked(form,'active') }; void mutate(value ? updateProduct({ ...input, id: value.id, updatedAt: value.updated_at }) : createProduct(input), true); }} />}
    {modal?.kind === 'extras' && <ExtrasModal product={data.products.find(product => product.id === modal.value.id) ?? modal.value} saving={saving} close={() => setModal(null)} mutate={mutate} />}
  </>;
}

function Overlay({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div role="dialog" aria-modal="true" aria-label={title} className="fixed inset-0 z-30 grid place-items-center bg-black/40 p-4"><Card className="max-h-[90dvh] w-full max-w-2xl overflow-y-auto"><div className="flex justify-between"><h2 className="text-lg font-black">{title}</h2><button aria-label="Fechar" onClick={close}>✕</button></div>{children}</Card></div>; }
const field = 'w-full rounded-xl border p-2';
function CategoryModal({ value, saving, close, submit }: { value?: AdminMenuCategory; saving: boolean; close: () => void; submit: (form: FormData, value?: AdminMenuCategory) => void }) { return <Overlay title={value ? 'Editar categoria' : 'Nova categoria'} close={close}><form className="mt-4 space-y-3" onSubmit={event => { event.preventDefault(); submit(new FormData(event.currentTarget), value); }}><label className="block text-sm">Nome<input name="name" defaultValue={value?.name} required minLength={2} maxLength={80} className={field}/></label><label className="block text-sm">Ordem<input name="sortOrder" type="number" defaultValue={value?.sort_order ?? 0} required className={field}/></label>{value && <label className="flex gap-2"><input name="active" type="checkbox" defaultChecked={value.active}/> Categoria ativa</label>}<Button disabled={saving} type="submit">Salvar</Button></form></Overlay>; }
function ProductModal({ value, categories, saving, close, submit }: { value?: AdminMenuProduct; categories: AdminMenuCategory[]; saving: boolean; close: () => void; submit: (form: FormData, value?: AdminMenuProduct) => void }) { return <Overlay title={value ? 'Editar produto' : 'Novo produto'} close={close}><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); submit(new FormData(event.currentTarget), value); }}><label className="text-sm">Nome<input name="name" defaultValue={value?.name} required className={field}/></label><label className="text-sm">Categoria<select name="categoryId" defaultValue={value?.category_id} required className={field}>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="text-sm sm:col-span-2">Descrição<textarea name="description" defaultValue={value?.description ?? ''} maxLength={500} className={field}/></label><label className="text-sm">Preço (R$)<input name="price" inputMode="decimal" defaultValue={value ? (value.price_cents / 100).toFixed(2).replace('.', ',') : '0,00'} required className={field}/></label><label className="text-sm">Imagem ou emoji<input name="imageUrl" defaultValue={value?.image_url ?? ''} maxLength={500} className={field}/></label><label className="text-sm">Ordem<input name="sortOrder" type="number" defaultValue={value?.sort_order ?? 0} required className={field}/></label><label className="flex items-center gap-2"><input name="active" type="checkbox" defaultChecked={value?.active ?? true}/> Produto ativo</label><Button disabled={saving || categories.length === 0} type="submit">Salvar</Button></form></Overlay>; }

function ExtrasModal({ product, saving, close, mutate }: { product: AdminMenuProduct; saving: boolean; close: () => void; mutate: (operation: Promise<MenuMutationResult>) => Promise<void> }) {
  const submitOption = (event: FormEvent<HTMLFormElement>, option?: AdminMenuOption) => { event.preventDefault(); const form = new FormData(event.currentTarget); const input = { productId: product.id, name: str(form,'name'), required: checked(form,'required'), minChoices: num(form,'minChoices'), maxChoices: num(form,'maxChoices') }; void mutate(option ? updateOption({ ...input, id: option.id, updatedAt: option.updated_at }) : createOption(input)); };
  const submitAddon = (event: FormEvent<HTMLFormElement>, addon?: AdminMenuAddon) => { event.preventDefault(); const form = new FormData(event.currentTarget); const optionId = str(form,'optionId') || null; const input = { productId: product.id, optionId, name: str(form,'name'), price: str(form,'price'), active: checked(form,'active'), sortOrder: num(form,'sortOrder') }; void mutate(addon ? updateAddon({ ...input, id: addon.id, updatedAt: addon.updated_at }) : createAddon(input)); };
  return <Overlay title={`Opções e adicionais · ${product.name}`} close={close}><section className="mt-4"><h3 className="font-bold">Grupos de opções</h3><div className="mt-2 space-y-3">{product.options.map(option => <OptionForm key={option.id} option={option} saving={saving} submit={submitOption}/>)}<OptionForm saving={saving} submit={submitOption}/></div></section><section className="mt-6 border-t pt-4"><h3 className="font-bold">Adicionais</h3><div className="mt-2 space-y-3">{product.addons.map(addon => <AddonForm key={addon.id} addon={addon} options={product.options} saving={saving} submit={submitAddon}/>)}<AddonForm options={product.options} saving={saving} submit={submitAddon}/></div></section></Overlay>;
}
function OptionForm({ option, saving, submit }: { option?: AdminMenuOption; saving: boolean; submit: (event: FormEvent<HTMLFormElement>, option?: AdminMenuOption) => void }) { return <form onSubmit={event => submit(event, option)} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-5"><input aria-label="Nome da opção" name="name" defaultValue={option?.name} placeholder="Nome do grupo" required className={`${field} sm:col-span-2`}/><input aria-label="Mínimo" name="minChoices" type="number" min="0" defaultValue={option?.min_choices ?? 0} required className={field}/><input aria-label="Máximo" name="maxChoices" type="number" min="0" defaultValue={option?.max_choices ?? 1} required className={field}/><label className="flex items-center gap-1 text-sm"><input name="required" type="checkbox" defaultChecked={option?.required}/> Obrigatório</label><Button disabled={saving} type="submit" className="sm:col-span-5">{option ? 'Atualizar opção' : '+ Criar opção'}</Button></form>; }
function AddonForm({ addon, options, saving, submit }: { addon?: AdminMenuAddon; options: AdminMenuOption[]; saving: boolean; submit: (event: FormEvent<HTMLFormElement>, addon?: AdminMenuAddon) => void }) { return <form onSubmit={event => submit(event, addon)} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-5"><input aria-label="Nome do adicional" name="name" defaultValue={addon?.name} placeholder="Nome" required className={field}/><select aria-label="Grupo do adicional" name="optionId" defaultValue={addon?.option_id ?? ''} className={field}><option value="">Sem grupo</option>{options.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select><input aria-label="Preço do adicional em reais" name="price" inputMode="decimal" defaultValue={addon ? (addon.price_cents / 100).toFixed(2).replace('.', ',') : '0,00'} required className={field}/><input aria-label="Ordem do adicional" name="sortOrder" type="number" defaultValue={addon?.sort_order ?? 0} required className={field}/><label className="flex items-center gap-1 text-sm"><input name="active" type="checkbox" defaultChecked={addon?.active ?? true}/> Ativo</label><Button disabled={saving} type="submit" className="sm:col-span-5">{addon ? 'Atualizar adicional' : '+ Criar adicional'}</Button></form>; }
