'use client';
import { useCallback,useRef,useState,type ReactNode } from 'react';
import { loadReports } from '@/app/admin/relatorios/actions';
import type { ReportResult } from '@/lib/admin-report-types';
import { Button,Card,Money } from '@/components/ui';
import { useVisiblePolling } from '@/lib/use-visible-polling';
type Period='today'|'7'|'30'|'custom';
const paymentLabels={pix:'Pix',cash:'Dinheiro',card:'Cartão'} as const;
const methodLabels={delivery:'Entrega',pickup:'Retirada'} as const;
const money=(c:number)=><Money value={c/100}/>;
function addDays(date:string,days:number){const value=new Date(`${date}T00:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10);}
function shortDate(date:string){return new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',day:'2-digit',month:'2-digit'}).format(new Date(`${date}T00:00:00Z`));}

export function ReportsAnalytics({initial}:{initial:ReportResult}){
  const [data,setData]=useState(initial.data??null),[error,setError]=useState(initial.error??null),[period,setPeriod]=useState<Period>('today'),[refreshing,setRefreshing]=useState(false);
  const [start,setStart]=useState(initial.data?.start_date??''),[end,setEnd]=useState(initial.data?.end_date??'');const busy=useRef(false);
  const refresh=useCallback(async(first=start,last=end)=>{if(busy.current)return;busy.current=true;setRefreshing(true);try{const result=await loadReports({start:first,end:last});if(result.data){setData(result.data);setStart(result.data.start_date);setEnd(result.data.end_date);setError(null)}else setError(result.error)}catch{setError('Conexão interrompida. Exibindo a última consulta recebida.')}finally{busy.current=false;setRefreshing(false)}},[start,end]);
  function choose(value:Period){setPeriod(value);if(value==='custom')return;const today=data?.business_date??end;void refresh(value==='today'?today:addDays(today,value==='7'?-6:-29),today);}
  useVisiblePolling(refresh,period==='today');
  if(!data)return <><Header period={period} choose={choose} refreshing={refreshing}/><Card className="mt-6"><p role="alert" className="text-red-700">{error??'Relatório indisponível.'}</p></Card></>;
  const peak=data.hours.reduce((best,row)=>row.received>best.received?row:best,{hour:0,received:0,revenue_cents:0});const maxRevenue=Math.max(1,...data.daily.map(day=>day.revenue_cents));
  return <><Header period={period} choose={choose} refreshing={refreshing}/>
    {period==='custom'&&<form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void refresh(String(form.get('start')??''),String(form.get('end')??''))}}><label className="text-sm">Início<input name="start" aria-label="Data inicial" type="date" value={start} onChange={e=>setStart(e.target.value)} className="mt-1 block rounded-xl border bg-white p-2"/></label><label className="text-sm">Fim<input name="end" aria-label="Data final" type="date" value={end} onChange={e=>setEnd(e.target.value)} className="mt-1 block rounded-xl border bg-white p-2"/></label><Button disabled={refreshing}>Aplicar período</Button></form>}
    {error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<p className="mt-3 text-xs text-stone-500">Período: {data.start_date.split('-').reverse().join('/')} a {data.end_date.split('-').reverse().join('/')} · America/Sao_Paulo</p>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Faturamento" value={money(data.metrics.revenue_cents)}/><Kpi label="Pedidos recebidos" value={data.metrics.orders_received}/><Kpi label="Pedidos válidos" value={data.metrics.valid_orders}/><Kpi label="Ticket médio" value={money(data.metrics.average_ticket_cents)}/><Kpi label="Clientes únicos" value={data.metrics.unique_customers}/><Kpi label="Cancelamentos" value={`${data.metrics.cancelled_orders} (${data.metrics.cancellation_rate_percent.toLocaleString('pt-BR')}%)`}/><Kpi label="Crescimento" value={data.metrics.growth_percent===null?'Sem base':`${data.metrics.growth_percent.toLocaleString('pt-BR')}%`}/><Kpi label="Período anterior" value={money(data.metrics.previous_revenue_cents)}/></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-black">Evolução diária</h2><div className="mt-6 flex h-44 items-end gap-1 overflow-x-auto">{data.daily.map(day=><div key={day.date} title={`${day.date}: ${day.revenue_cents} centavos`} className="flex min-w-6 flex-1 flex-col justify-end"><div className="rounded-t bg-orange-300" style={{height:`${Math.max(day.revenue_cents?8:1,day.revenue_cents/maxRevenue*100)}%`}}/><small className="mt-1 text-center text-[10px] text-stone-500">{shortDate(day.date)}</small></div>)}</div><p className="mt-3 text-xs text-stone-500">Dias sem movimento permanecem na série com zero.</p></Card>
    <Card><h2 className="font-black">Formas de pagamento</h2>{(['pix','card','cash'] as const).map(method=>{const row=data.payments.find(x=>x.method===method);return <Line key={method} label={paymentLabels[method]} detail={`${row?.quantity??0} pedidos · ${(row?.percent??0).toLocaleString('pt-BR')}%`} cents={row?.revenue_cents??0}/>})}</Card>
    <Card><h2 className="font-black">Entrega x retirada</h2>{(['delivery','pickup'] as const).map(method=>{const row=data.delivery_methods.find(x=>x.method===method);return <Line key={method} label={methodLabels[method]} detail={`${row?.quantity??0} pedidos · ${(row?.percent??0).toLocaleString('pt-BR')}%`} cents={row?.revenue_cents??0}/>})}</Card>
    <Card><h2 className="font-black">Clientes</h2><p className="mt-3 text-sm">Novos: <b>{data.customers.new}</b> · Recorrentes: <b>{data.customers.recurring}</b></p>{data.customers.top.length===0?<Empty/>:data.customers.top.map((c,i)=><div key={c.id} className="mt-4 flex justify-between gap-3"><span>{i+1}. {c.name}<small className="block text-stone-500">{c.orders_count} pedidos</small></span><b>{money(c.spent_cents)}</b></div>)}<p className="mt-5 text-sm text-stone-500">Pico: {peak.received?`${String(peak.hour).padStart(2,'0')}h–${String((peak.hour+1)%24).padStart(2,'0')}h · ${peak.received} pedidos`:'Sem movimento'}</p></Card>
    <Card className="lg:col-span-2"><h2 className="font-black">Produtos mais vendidos</h2>{data.products.length===0?<Empty/>:data.products.map((p,i)=><div key={p.name} className="mt-4 grid gap-1 border-b pb-3 sm:grid-cols-[1fr_auto_auto]"><span>{i+1}. {p.name} · <b>{p.quantity} un.</b></span><span className="text-sm text-stone-500">Produtos {money(p.product_revenue_cents)} + adicionais {money(p.addon_revenue_cents)}</span><b>{money(p.total_revenue_cents)}</b></div>)}</Card></div>
  </>;
}
function Header({period,choose,refreshing}:{period:Period;choose:(p:Period)=>void;refreshing:boolean}){return <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-black">Relatórios</h1><p className="mt-1 text-stone-600">Análise real da operação por período.</p></div><select aria-label="Período do relatório" value={period} disabled={refreshing} onChange={e=>choose(e.target.value as Period)} className="rounded-xl border bg-white px-3"><option value="today">Hoje</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="custom">Período personalizado</option></select></div>}
function Kpi({label,value}:{label:string;value:ReactNode}){return <Card><p className="text-sm text-stone-500">{label}</p><div className="mt-2 text-xl font-black">{value}</div></Card>}
function Line({label,detail,cents}:{label:string;detail:string;cents:number}){return <div className="mt-4 flex justify-between gap-3"><span>{label}<small className="block text-stone-500">{detail}</small></span><b>{money(cents)}</b></div>}
function Empty(){return <p className="mt-4 text-sm text-stone-500">Sem movimento no período.</p>}
