'use client';

import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { loadWhatsAppCenter, loadWhatsAppMessages, queueWhatsAppMessage } from '@/app/admin/whatsapp/actions';
import { Money } from '@/components/ui';
import { ORDER_STATUS_LABELS, PAYMENT_LABELS, type OrderStatus } from '@/lib/admin-order-types';
import type { WhatsAppCenterData, WhatsAppCenterResult, WhatsAppConversation, WhatsAppConversationState, WhatsAppMessage, WhatsAppOrder } from '@/lib/admin-whatsapp-types';
import { buildWhatsAppManualLink, buildWhatsAppMessage, normalizeCustomerPhone, normalizeWhatsAppIdentity, resolveWhatsAppOutboundMode, suggestedTemplate, WHATSAPP_MESSAGE_MAX_LENGTH, WHATSAPP_TEMPLATE_IDS, WHATSAPP_TEMPLATE_LABELS, type MessageContext, type WhatsAppTemplateId } from '@/lib/whatsapp';
import { useVisiblePolling } from '@/lib/use-visible-polling';

const time = new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Sao_Paulo', hour: '2-digit', minute: '2-digit' });
const field = 'rounded-xl border border-stone-300 bg-white px-3 py-2 text-sm text-stone-950 outline-none placeholder:text-stone-500 focus-visible:border-brand-900 focus-visible:ring-2 focus-visible:ring-emerald-200';
type InboxFilter = 'all' | WhatsAppConversationState;
type InboxTab = 'contacts' | 'groups';
type Entry = { id: string; kind: 'conversation'; conversation: WhatsAppConversation } | { id: string; kind: 'fallback'; order: WhatsAppOrder };
const filters: { id: InboxFilter; label: string }[] = [{ id: 'all', label: 'Todas' }, { id: 'new', label: 'Novas' }, { id: 'waiting', label: 'Aguardando' }, { id: 'active', label: 'Atendendo' }, { id: 'resolved', label: 'Resolvidas' }];
const stateLabels: Record<WhatsAppConversationState, string> = { new: 'Nova', waiting: 'Aguardando', active: 'Atendendo', resolved: 'Resolvida' };
const messageStatusLabels = { received: 'Recebida', queued: 'Enfileirada', accepted: 'Aceita', sent: 'Enviada', delivered: 'Entregue', read: 'Lida', failed: 'Falhou' } as const;

function fallbackState(status: OrderStatus): WhatsAppConversationState {
  if (status === 'new') return 'new'; if (status === 'confirmed' || status === 'ready') return 'waiting';
  if (status === 'preparing' || status === 'out_for_delivery') return 'active'; return 'resolved';
}
function entryState(entry: Entry) { return entry.kind === 'conversation' ? entry.conversation.state : fallbackState(entry.order.status); }
function entryOrder(entry: Entry) { return entry.kind === 'conversation' ? entry.conversation.latest_order : entry.order; }
function entryName(entry: Entry) { const order = entryOrder(entry); return entry.kind === 'conversation' ? entry.conversation.customer?.name ?? order?.customer_name_snapshot ?? entry.conversation.phone_e164 : entry.order.customer_name_snapshot; }
function entryPhone(entry: Entry) { return entry.kind === 'conversation' ? entry.conversation.phone_e164 : entry.order.whatsapp_snapshot; }
function entryDate(entry: Entry) { return entry.kind === 'conversation' ? entry.conversation.last_message_at ?? entry.conversation.last_inbound_at ?? new Date(0).toISOString() : entry.order.created_at; }
function context(order: WhatsAppOrder, data: WhatsAppCenterData): MessageContext { return { customerName: order.customer_name_snapshot, orderNumber: order.order_number, totalCents: order.total_cents, deliveryMethod: order.delivery_method, restaurantName: data.restaurant_name, deliveryMinutesMin: data.delivery_minutes_min, deliveryMinutesMax: data.delivery_minutes_max }; }

export function WhatsAppCenter({ initial }: { initial: WhatsAppCenterResult }) {
  const [data, setData] = useState(initial.data ?? null); const [error, setError] = useState(initial.error ?? null);
  const [refreshing, setRefreshing] = useState(false); const [tab, setTab] = useState<InboxTab>('contacts');
  const [filter, setFilter] = useState<InboxFilter>('all'); const [query, setQuery] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(null); const [messages, setMessages] = useState<WhatsAppMessage[]>([]);
  const [historyLoading, setHistoryLoading] = useState(false); const [hasOlder, setHasOlder] = useState(false); const [template, setTemplate] = useState<WhatsAppTemplateId>('custom');
  const [message, setMessage] = useState(''); const [sending, setSending] = useState(false); const busy = useRef(false); const messageKey = useRef('');

  const entries = useMemo<Entry[]>(() => {
    if (!data) return [];
    if (data.conversations.length) return data.conversations.map(conversation => ({ id: conversation.id, kind: 'conversation', conversation }));
    return data.fallback_orders.map(order => ({ id: `order:${order.id}`, kind: 'fallback', order }));
  }, [data]);
  const selected = entries.find(entry => entry.id === selectedId) ?? null;

  const refresh = useCallback(async () => {
    if (busy.current) return; busy.current = true; setRefreshing(true);
    try { const result = await loadWhatsAppCenter(); if (result.data) { setData(result.data); setError(null); } else setError(result.error); }
    catch { setError('Conexão interrompida. Exibindo os últimos dados recebidos.'); }
    finally { busy.current = false; setRefreshing(false); }
  }, []);
  useVisiblePolling(refresh);

  useEffect(() => {
    if (!selected || selected.kind !== 'conversation') { setMessages([]); setHasOlder(false); return; }
    let active = true; setHistoryLoading(true);
    void loadWhatsAppMessages({ conversationId: selected.conversation.id }).then(result => { if (!active) return; if (result.data) { setMessages(result.data); setHasOlder(result.data.length === 50); } else setError(result.error); }).finally(() => { if (active) setHistoryLoading(false); });
    return () => { active = false; };
  }, [selected]);

  useEffect(() => {
    if (!selected || !data) { messageKey.current = ''; setMessage(''); setTemplate('custom'); return; }
    const order = entryOrder(selected); const key = `${selected.id}:${order?.status ?? 'none'}`;
    if (messageKey.current === key) return; messageKey.current = key;
    if (order) { const next = suggestedTemplate(order.status); setTemplate(next); setMessage(buildWhatsAppMessage(next, context(order, data))); }
    else { setTemplate('custom'); setMessage(''); }
  }, [selected, data]);

  const counts = useMemo(() => entries.reduce<Record<InboxFilter, number>>((result, entry) => { result.all += 1; result[entryState(entry)] += 1; return result; }, { all: 0, new: 0, waiting: 0, active: 0, resolved: 0 }), [entries]);
  const visible = useMemo(() => { const needle = query.trim().toLocaleLowerCase('pt-BR'); const digits = query.replace(/\D/g, ''); return entries.filter(entry => (filter === 'all' || entryState(entry) === filter) && (!needle || entryName(entry).toLocaleLowerCase('pt-BR').includes(needle) || (!!digits && entryPhone(entry).replace(/\D/g, '').includes(digits)) || String(entryOrder(entry)?.order_number ?? '').includes(needle))); }, [entries, filter, query]);

  function chooseTemplate(value: WhatsAppTemplateId) { setTemplate(value); const order = selected ? entryOrder(selected) : null; if (order && data && value !== 'custom') setMessage(buildWhatsAppMessage(value, context(order, data))); }
  async function queueOfficial() {
    if (!selected || selected.kind !== 'conversation' || !data?.official_available || sending) return;
    setSending(true); const result = await queueWhatsAppMessage({ conversationId: selected.conversation.id, orderId: selected.conversation.latest_order_id, content: message, templateId: template, idempotencyKey: `manual:${crypto.randomUUID()}` });
    if (result.error) setError(result.error); else { const history = await loadWhatsAppMessages({ conversationId: selected.conversation.id }); if (history.data) setMessages(history.data); }
    setSending(false);
  }
  async function loadOlder() {
    if (!selected || selected.kind !== 'conversation' || historyLoading || !messages[0]) return;
    setHistoryLoading(true);
    const result = await loadWhatsAppMessages({ conversationId: selected.conversation.id, beforeCreatedAt: messages[0].created_at, beforeId: messages[0].id });
    if (result.data) { const known = new Set(messages.map(item => item.id)); setMessages([...result.data.filter(item => !known.has(item.id)), ...messages]); setHasOlder(result.data.length === 50); }
    else setError(result.error);
    setHistoryLoading(false);
  }

  if (!data) return <Unavailable refreshing={refreshing} refresh={refresh} error={error} />;
  return <div className="mx-auto flex max-w-[1500px] flex-col"><PageHeader refreshing={refreshing} refresh={refresh} />
    <ConnectionStatus data={data} />
    {!data.integration_enabled && <div role="status" className="mt-4 rounded-2xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm font-bold text-amber-950">Envio oficial ainda não ativado. Automações {data.automations_enabled ? 'habilitadas no banco' : 'desligadas'}. O envio manual por wa.me continua disponível e nenhuma mensagem é marcada automaticamente como enviada.</div>}
    {error && <p role="alert" className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-800">{error}</p>}
    <div className="mt-4 grid min-h-[calc(100dvh-12rem)] overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-[0_18px_60px_rgba(41,55,38,0.09)] lg:h-[calc(100dvh-11rem)] lg:min-h-[620px] lg:grid-cols-[340px_minmax(0,1fr)]">
      <ConversationList entries={visible} total={entries.length} selectedId={selectedId} tab={tab} filter={filter} counts={counts} query={query} hiddenOnMobile={Boolean(selected)} usingFallback={!data.conversations.length} onTab={value => { setTab(value); setSelectedId(null); }} onFilter={setFilter} onQuery={setQuery} onSelect={setSelectedId} />
      <ChatPanel entry={selected} messages={messages} historyLoading={historyLoading} hasOlder={hasOlder} integrationEnabled={data.official_available} template={template} message={message} hiddenOnMobile={!selected} sending={sending} onBack={() => setSelectedId(null)} onLoadOlder={() => void loadOlder()} onTemplate={chooseTemplate} onMessage={value => { setMessage(value); setTemplate('custom'); }} onQueue={() => void queueOfficial()} />
    </div></div>;
}

function PageHeader({ refreshing, refresh }: { refreshing: boolean; refresh: () => Promise<void> }) { return <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-terracotta-700">Atendimento</p><h1 className="mt-1 text-2xl font-black text-brand-950 sm:text-3xl">WhatsApp</h1><p className="mt-1 text-sm font-medium text-stone-600">Atendimento humano com contexto de clientes e pedidos.</p></div><button disabled={refreshing} onClick={() => void refresh()} className="min-h-11 rounded-xl border border-brand-900 bg-white px-4 text-sm font-black text-brand-900 hover:bg-brand-50 disabled:opacity-60">{refreshing ? 'Atualizando...' : 'Atualizar conversas'}</button></header>; }

function ConnectionStatus({ data }: { data: WhatsAppCenterData }) {
  const latestSync = data.sync_runs[0];
  const activeSync = latestSync && (latestSync.state === 'pending' || latestSync.state === 'processing') ? latestSync : null;
  if (data.connection_state === 'removed' || data.connection_state === 'attention') return <div role="alert" className="mt-4 rounded-2xl border border-red-300 bg-red-50 px-4 py-3 text-sm font-bold text-red-950">Integração removida ou requer atenção{data.last_account_event ? ` · ${data.last_account_event}` : ''}.</div>;
  if (activeSync) return <div role="status" className="mt-4 rounded-2xl border border-sky-300 bg-sky-50 px-4 py-3 text-sm font-bold text-sky-950">Sincronizando {activeSync.sync_type === 'history' ? 'histórico' : 'contatos'}{activeSync.progress === null ? '' : ` · ${activeSync.progress}%`}.</div>;
  const completedSync = latestSync?.state === 'completed' ? ` · ${latestSync.sync_type === 'history' ? 'Histórico' : 'Contatos'} sincronizado.` : '';
  if (data.connection_state === 'coexistence_active') return <div role="status" className="mt-4 rounded-2xl border border-emerald-300 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-950">Coexistência ativa{completedSync}</div>;
  if (data.connection_state === 'connected') return <div role="status" className="mt-4 rounded-2xl border border-emerald-300 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-950">Integração conectada{completedSync}</div>;
  if (completedSync) return <div role="status" className="mt-4 rounded-2xl border border-stone-300 bg-white px-4 py-3 text-sm font-bold text-stone-800">{completedSync.slice(3)}</div>;
  return null;
}

type ListProps = { entries: Entry[]; total: number; selectedId: string | null; tab: InboxTab; filter: InboxFilter; counts: Record<InboxFilter, number>; query: string; hiddenOnMobile: boolean; usingFallback: boolean; onTab: (v: InboxTab) => void; onFilter: (v: InboxFilter) => void; onQuery: (v: string) => void; onSelect: (id: string) => void };
function ConversationList({ entries, total, selectedId, tab, filter, counts, query, hiddenOnMobile, usingFallback, onTab, onFilter, onQuery, onSelect }: ListProps) { return <aside aria-label="Conversas" className={`${hiddenOnMobile ? 'hidden' : 'flex'} min-h-0 flex-col border-stone-200 bg-stone-50/70 lg:flex lg:border-r`}><div className="border-b border-stone-200 bg-white p-4 sm:p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-brand-950">Conversas</h2><span className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-black text-brand-900">{total}</span></div><div role="tablist" className="mt-4 grid grid-cols-2 rounded-xl bg-stone-100 p-1"><Tab active={tab === 'contacts'} onClick={() => onTab('contacts')}>Contatos</Tab><Tab active={tab === 'groups'} onClick={() => onTab('groups')}>Grupos</Tab></div><label className="mt-4 block"><span className="sr-only">Pesquisar conversa</span><input value={query} onChange={event => onQuery(event.target.value)} placeholder="Pesquisar conversa..." className={`${field} min-h-11 w-full`} /></label><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{filters.map(item => <button key={item.id} aria-pressed={filter === item.id} onClick={() => onFilter(item.id)} className={`min-h-9 shrink-0 rounded-full border px-3 text-xs font-black ${filter === item.id ? 'border-brand-900 bg-brand-900 text-white' : 'border-stone-300 bg-white text-stone-700'}`}>{item.label} {counts[item.id]}</button>)}</div>{usingFallback && <p className="mt-2 text-[11px] font-medium text-stone-600">Sem conversas oficiais armazenadas; exibindo pedidos recentes como atalhos manuais.</p>}</div><div className="min-h-0 flex-1 overflow-y-auto">{tab === 'groups' ? <Empty title="Nenhum grupo" /> : entries.length ? <ul>{entries.map(entry => <EntryItem key={entry.id} entry={entry} selected={entry.id === selectedId} onSelect={() => onSelect(entry.id)} />)}</ul> : <Empty title="Nenhuma conversa" />}</div></aside>; }
function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: ReactNode }) { return <button role="tab" aria-selected={active} onClick={onClick} className={`min-h-10 rounded-lg px-3 text-sm font-black ${active ? 'bg-white text-brand-950 shadow-sm' : 'text-stone-600'}`}>{children}</button>; }
function EntryItem({ entry, selected, onSelect }: { entry: Entry; selected: boolean; onSelect: () => void }) { const order = entryOrder(entry); const unread = entry.kind === 'conversation' ? entry.conversation.unread_count : 0; return <li className="border-b border-stone-200"><button aria-current={selected ? 'true' : undefined} onClick={onSelect} className={`w-full border-l-4 p-4 text-left ${selected ? 'border-brand-900 bg-brand-50' : 'border-transparent bg-white hover:bg-stone-50'}`}><div className="flex justify-between gap-3"><span className="min-w-0"><strong className="block truncate text-sm text-stone-950">{entryName(entry)}</strong><span className="block truncate text-xs text-stone-600">{entryPhone(entry)}</span></span><time className="shrink-0 text-[11px] font-bold text-stone-600">{time.format(new Date(entryDate(entry)))}</time></div><div className="mt-2 flex items-center justify-between"><span className="text-xs font-black text-terracotta-700">{order ? `Pedido #${order.order_number}` : stateLabels[entryState(entry)]}</span>{unread > 0 && <span className="rounded-full bg-brand-900 px-2 py-0.5 text-[10px] font-black text-white">{unread} nova{unread > 1 ? 's' : ''}</span>}</div></button></li>; }
function Empty({ title }: { title: string }) { return <div className="grid min-h-64 place-items-center p-8 text-center"><div><span className="text-3xl text-stone-500">◎</span><h3 className="mt-3 font-black text-stone-900">{title}</h3><p className="mt-1 text-sm text-stone-600">As mensagens aparecerão aqui quando forem recebidas.</p></div></div>; }

type ChatProps = { entry: Entry | null; messages: WhatsAppMessage[]; historyLoading: boolean; hasOlder: boolean; integrationEnabled: boolean; template: WhatsAppTemplateId; message: string; hiddenOnMobile: boolean; sending: boolean; onBack: () => void; onLoadOlder: () => void; onTemplate: (v: WhatsAppTemplateId) => void; onMessage: (v: string) => void; onQueue: () => void };
function ChatPanel({ entry, messages, historyLoading, hasOlder, integrationEnabled, template, message, hiddenOnMobile, sending, onBack, onLoadOlder, onTemplate, onMessage, onQueue }: ChatProps) { if (!entry) return <main className={`${hiddenOnMobile ? 'hidden' : 'grid'} min-h-[520px] place-items-center bg-[#f8f5ed] p-8 text-center lg:grid`}><div><span className="text-4xl text-brand-900">◌</span><h2 className="mt-4 text-xl font-black text-brand-950">Suas conversas</h2><p className="mt-2 text-sm text-stone-700">Selecione um contato para visualizar o histórico e responder.</p></div></main>; const order = entryOrder(entry); const manualTarget = entry.kind === 'conversation' ? normalizeWhatsAppIdentity(entry.conversation.wa_id) : normalizeCustomerPhone(entry.order.whatsapp_snapshot); const url = buildWhatsAppManualLink(entry.kind === 'conversation' ? { whatsappIdentity: entry.conversation.wa_id } : { customerPhone: entry.order.whatsapp_snapshot }, message); const serviceWindowExpiresAt = entry.kind === 'conversation' ? entry.conversation.service_window_expires_at : null; const outboundMode = resolveWhatsAppOutboundMode({ integrationEnabled, serviceWindowExpiresAt, templateId: template }); return <main className={`${hiddenOnMobile ? 'hidden' : 'flex'} min-h-0 flex-col bg-[#f8f5ed] lg:flex`}><ChatHeader entry={entry} serviceWindowExpiresAt={serviceWindowExpiresAt} onBack={onBack} /><div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-6"><div className="mx-auto max-w-3xl">{hasOlder && <div className="mb-4 text-center"><button disabled={historyLoading} onClick={onLoadOlder} className="min-h-10 rounded-xl border border-stone-300 bg-white px-4 text-xs font-black text-brand-900 disabled:opacity-60">Carregar mensagens anteriores</button></div>}{historyLoading && <p className="text-center text-sm font-bold text-stone-600">Carregando histórico...</p>}{messages.map(item => <MessageBubble key={item.id} message={item} />)}{!messages.length && order && <OrderCard order={order} />}{!messages.length && !order && !historyLoading && <p className="rounded-xl bg-white p-4 text-center text-sm text-stone-600">Conversa sem mensagens carregadas.</p>}</div></div><Composer realConversation={entry.kind === 'conversation'} integrationEnabled={integrationEnabled} outboundMode={outboundMode} template={template} message={message} manualTarget={manualTarget} url={url} sending={sending} onTemplate={onTemplate} onMessage={onMessage} onQueue={onQueue} /></main>; }
function ChatHeader({ entry, serviceWindowExpiresAt, onBack }: { entry: Entry; serviceWindowExpiresAt: string | null; onBack: () => void }) { const order = entryOrder(entry); const expiresAt = serviceWindowExpiresAt ? new Date(serviceWindowExpiresAt) : null; const windowOpen = !!expiresAt && expiresAt > new Date(); return <header className="flex min-h-[76px] flex-wrap items-center gap-3 border-b border-stone-200 bg-white px-4 py-3"><button onClick={onBack} className="min-h-11 rounded-xl px-2 text-sm font-black text-brand-900 lg:hidden">← Voltar</button><div className="grid size-10 shrink-0 place-items-center rounded-full bg-brand-900 font-black text-white">{entryName(entry).charAt(0).toUpperCase()}</div><div className="min-w-0 flex-1"><h2 className="truncate font-black text-stone-950">{entryName(entry)}</h2><p className="truncate text-xs text-stone-600">{entryPhone(entry)}{order ? ` · Pedido #${order.order_number}` : ''}</p></div>{entry.kind === 'conversation' && <span className={`rounded-full border px-3 py-1 text-xs font-black ${windowOpen ? 'border-emerald-300 bg-emerald-100 text-emerald-950' : 'border-amber-300 bg-amber-100 text-amber-950'}`}>{windowOpen ? `Janela de atendimento aberta até ${time.format(expiresAt)}` : 'Janela encerrada — use um modelo aprovado.'}</span>}</header>; }
function MessageBubble({ message }: { message: WhatsAppMessage }) { const outbound = message.direction === 'outbound'; const origin = message.message_origin === 'business_app' ? 'Enviada pelo WhatsApp Business' : message.message_origin === 'history' ? 'Histórico importado' : null; return <div className={`mb-4 max-w-[88%] rounded-2xl border p-4 text-sm shadow-sm sm:max-w-[72%] ${outbound ? 'ml-auto rounded-br-md border-emerald-200 bg-[#dcf8c6]' : 'rounded-bl-md border-stone-200 bg-white'}`}><p className="whitespace-pre-wrap leading-relaxed text-stone-900">{message.content_text || (message.template_name ? `Template: ${message.template_name}` : 'Mensagem sem prévia de texto')}</p>{origin && <p className="mt-2 text-[10px] font-black uppercase tracking-wide text-stone-600">{origin}</p>}<div className="mt-2 flex justify-end gap-2 text-[10px] font-bold text-stone-600"><time>{time.format(new Date(message.created_at))}</time><span>{messageStatusLabels[message.status]}</span>{message.automatic && <span>Automática</span>}</div>{message.failure_message && <p className="mt-2 text-xs font-bold text-red-800">{message.failure_message}</p>}</div>; }
function OrderCard({ order }: { order: WhatsAppOrder }) { return <div className="max-w-[88%] rounded-2xl border border-stone-200 bg-white p-4 text-sm text-stone-700 shadow-sm"><p className="font-black text-brand-950">Contexto do pedido</p><p>Pedido #{order.order_number} · {ORDER_STATUS_LABELS[order.status]}</p><p>{order.delivery_method === 'delivery' ? 'Entrega' : 'Retirada'} · {PAYMENT_LABELS[order.payment_method]}</p><p className="mt-2 font-black text-brand-900"><Money value={order.total_cents / 100} /></p><details className="mt-3"><summary className="cursor-pointer font-black text-brand-900">Ver itens</summary><ul className="mt-2 space-y-1">{order.items.map(item => <li key={item.id}>{item.quantity}× {item.product_name_snapshot}{item.addons.map(addon => <small key={addon.id} className="block pl-3">+ {addon.quantity}× {addon.addon_name_snapshot}</small>)}</li>)}</ul></details></div>; }

type ComposerProps = { realConversation: boolean; integrationEnabled: boolean; outboundMode: ReturnType<typeof resolveWhatsAppOutboundMode>; template: WhatsAppTemplateId; message: string; manualTarget: string | null; url: string | null; sending: boolean; onTemplate: (v: WhatsAppTemplateId) => void; onMessage: (v: string) => void; onQueue: () => void };
function Composer({ realConversation, integrationEnabled, outboundMode, template, message, manualTarget, url, sending, onTemplate, onMessage, onQueue }: ComposerProps) { const officialDisabled = !integrationEnabled || !realConversation || !message.trim() || sending || outboundMode.mode === 'blocked' || outboundMode.mode === 'disabled'; const officialLabel = sending ? 'Enfileirando...' : outboundMode.mode === 'disabled' ? 'Envio oficial ainda não ativado' : outboundMode.mode === 'blocked' ? 'Modelo aprovado necessário' : outboundMode.mode === 'template' ? 'Enviar modelo oficial' : 'Enviar pela API'; return <footer className="border-t border-stone-200 bg-white p-3 sm:p-4"><div className="mx-auto max-w-3xl"><div className="flex flex-wrap items-center gap-2"><label className="text-xs font-black text-stone-700">Mensagem rápida <select value={template} onChange={event => onTemplate(event.target.value as WhatsAppTemplateId)} className={`${field} ml-2 min-h-10 py-1.5`}>{WHATSAPP_TEMPLATE_IDS.map(value => <option key={value} value={value}>{WHATSAPP_TEMPLATE_LABELS[value]}</option>)}</select></label><button type="button" onClick={() => void navigator.clipboard.writeText(message)} disabled={!message.trim()} className="min-h-10 rounded-xl border border-stone-300 px-3 text-xs font-black text-brand-900 disabled:opacity-50">Copiar</button></div><textarea value={message} maxLength={WHATSAPP_MESSAGE_MAX_LENGTH} onChange={event => onMessage(event.target.value)} rows={2} placeholder="Digite uma mensagem..." className={`${field} mt-3 block min-h-[60px] w-full resize-y`} /><div className="mt-2 flex flex-wrap justify-end gap-2"><button type="button" disabled={officialDisabled} onClick={onQueue} className="min-h-11 rounded-xl bg-brand-900 px-4 text-sm font-black text-white disabled:cursor-not-allowed disabled:bg-stone-300 disabled:text-stone-600">{officialLabel}</button>{url ? <a href={url} target="_blank" rel="noopener noreferrer" className="grid min-h-11 place-items-center rounded-xl bg-green-800 px-4 text-sm font-black text-white">Enviar pelo WhatsApp</a> : <button disabled className="min-h-11 rounded-xl bg-stone-300 px-4 text-sm font-black text-stone-600">WhatsApp indisponível</button>}</div>{!manualTarget && <p role="alert" className="mt-2 text-xs font-semibold text-red-800">Não foi possível determinar um destino seguro para o WhatsApp.</p>}<p className="mt-2 text-[11px] font-medium text-stone-600">O botão “Enviar pelo WhatsApp” abre wa.me para revisão manual e não registra entrega ou leitura.</p></div></footer>; }
function Unavailable({ refreshing, refresh, error }: { refreshing: boolean; refresh: () => Promise<void>; error: string | null }) { return <div><PageHeader refreshing={refreshing} refresh={refresh} /><p role="alert" className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-5 font-medium text-red-800">{error ?? 'Central indisponível.'}</p></div>; }
